C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Arch_Inst_0_SR.dds -alpha extract T_M_Arch_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Arch_Inst_2_0_SR.dds -alpha extract T_M_Arch_Inst_2_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Arch_Inst_Red_0_SR.dds -alpha extract T_M_Arch_Inst_Red_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Arch_Inst_Red_1_SR.dds -alpha extract T_M_Arch_Inst_Red_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Arch_Inst_Red_2_0_SR.dds -alpha extract T_M_Arch_Inst_Red_2_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_0_SR.dds -alpha extract T_M_BottomTrim_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_1_SR.dds -alpha extract T_M_BottomTrim_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_2_SR.dds -alpha extract T_M_BottomTrim_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_3_SR.dds -alpha extract T_M_BottomTrim_Inst_3_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_4_SR.dds -alpha extract T_M_BottomTrim_Inst_4_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_5_SR.dds -alpha extract T_M_BottomTrim_Inst_5_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_6_SR.dds -alpha extract T_M_BottomTrim_Inst_6_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_Black_0_SR.dds -alpha extract T_M_BottomTrim_Inst_Black_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_BottomTrim_Inst_UTile4_0_SR.dds -alpha extract T_M_BottomTrim_Inst_UTile4_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Dome_2_0_SR.dds -alpha extract T_M_Dome_2_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Dome_2_1_SR.dds -alpha extract T_M_Dome_2_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Dome_2_2_SR.dds -alpha extract T_M_Dome_2_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Dome_Inst_0_SR.dds -alpha extract T_M_Dome_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Dome_Inst_1_SR.dds -alpha extract T_M_Dome_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FirePit_Inst_0_SR.dds -alpha extract T_M_FirePit_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FirePit_Inst_Glow_0_SR.dds -alpha extract T_M_FirePit_Inst_Glow_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FirePit_Inst_nofire_0_SR.dds -alpha extract T_M_FirePit_Inst_nofire_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_0_SR.dds -alpha extract T_M_FloorTiles1_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_1_SR.dds -alpha extract T_M_FloorTiles1_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_2_SR.dds -alpha extract T_M_FloorTiles1_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_Blue_0_SR.dds -alpha extract T_M_FloorTiles1_Inst_Blue_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_Blue_1_SR.dds -alpha extract T_M_FloorTiles1_Inst_Blue_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_Inst2_0_SR.dds -alpha extract T_M_FloorTiles1_Inst_Inst2_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_Inst2_1_SR.dds -alpha extract T_M_FloorTiles1_Inst_Inst2_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles1_Inst_Inst2_2_SR.dds -alpha extract T_M_FloorTiles1_Inst_Inst2_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles2_Inst_0_SR.dds -alpha extract T_M_FloorTiles2_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles2_Inst_Inst_Inst_0_SR.dds -alpha extract T_M_FloorTiles2_Inst_Inst_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_FloorTiles2_Inst_REd_0_SR.dds -alpha extract T_M_FloorTiles2_Inst_REd_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Pillar_Inst_0_SR.dds -alpha extract T_M_Pillar_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Pillar_Inst_Colored_0_SR.dds -alpha extract T_M_Pillar_Inst_Colored_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Railing_Inst_0_SR.dds -alpha extract T_M_Railing_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Railing_Inst_1_SR.dds -alpha extract T_M_Railing_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Railing_Inst_2_SR.dds -alpha extract T_M_Railing_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Rocks_Inst_0_SR.dds -alpha extract T_M_Rocks_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Rocks_Inst_1_SR.dds -alpha extract T_M_Rocks_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Rocks_Inst_2_SR.dds -alpha extract T_M_Rocks_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Shield_Inst_0_SR.dds -alpha extract T_M_Shield_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_0_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_10_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_10_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_11_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_11_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_12_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_12_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_1_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_2_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_3_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_3_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_4_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_4_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_5_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_5_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_6_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_6_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_7_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_7_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_8_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_8_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Soul_Rocks2_Inst_9_SR.dds -alpha extract T_M_Soul_Rocks2_Inst_9_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Stairs_Inst_0_SR.dds -alpha extract T_M_Stairs_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Statue_Inst_0_SR.dds -alpha extract T_M_Statue_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_0_SR.dds -alpha extract T_M_StoneBrickWall_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_1_SR.dds -alpha extract T_M_StoneBrickWall_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_2_SR.dds -alpha extract T_M_StoneBrickWall_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_3_SR.dds -alpha extract T_M_StoneBrickWall_Inst_3_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_4_SR.dds -alpha extract T_M_StoneBrickWall_Inst_4_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_5_SR.dds -alpha extract T_M_StoneBrickWall_Inst_5_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_6_SR.dds -alpha extract T_M_StoneBrickWall_Inst_6_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_7_SR.dds -alpha extract T_M_StoneBrickWall_Inst_7_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_8_SR.dds -alpha extract T_M_StoneBrickWall_Inst_8_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneBrickWall_Inst_9_SR.dds -alpha extract T_M_StoneBrickWall_Inst_9_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_StoneCeiling_Inst_0_SR.dds -alpha extract T_M_StoneCeiling_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_TreeTrunk01_Inst_0_SR.dds -alpha extract T_M_TreeTrunk01_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_TreeTrunk01_Inst_1_SR.dds -alpha extract T_M_TreeTrunk01_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Tree_Branches_0_SR.dds -alpha extract T_M_Tree_Branches_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Tree_Branches_Inst_0_SR.dds -alpha extract T_M_Tree_Branches_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_0_SR.dds -alpha extract T_M_Trim_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_1_SR.dds -alpha extract T_M_Trim_Inst_1_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_2_SR.dds -alpha extract T_M_Trim_Inst_2_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_3_SR.dds -alpha extract T_M_Trim_Inst_3_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_4_SR.dds -alpha extract T_M_Trim_Inst_4_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_5_SR.dds -alpha extract T_M_Trim_Inst_5_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_6_SR.dds -alpha extract T_M_Trim_Inst_6_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_7_SR.dds -alpha extract T_M_Trim_Inst_7_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_8_SR.dds -alpha extract T_M_Trim_Inst_8_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_M_Trim_Inst_Inst_0_SR.dds -alpha extract T_M_Trim_Inst_Inst_0_R.dds
C:\Users\MJP\Desktop\Utilities\ImageMagick\convert.exe T_Soul_Tree011M_Inst_0_SR.dds -alpha extract T_Soul_Tree011M_Inst_0_R.dds